--- # Setup a default user - needs to be run as root.
- name: create deploy user
  user:
    name="{{ user }}"
    groups=adm,dialout,cdrom,floppy,audio,dip,video,plugdev,netdev,sudo
    append=yes
    state=present
    shell=/bin/bash

- name: add ssh keys users_sysadmin
  authorized_key:
    user={{ user }}
    key="{{ lookup('file', inventory_dir + '/../files/keys/' + item + '.pub') }}"
    state=present
  with_flattened: "{{ users_sysadmin }}"
  when: ssh_key_path is undefined

# Add ssh key path to run playbook command with --extra-vars
# ex.: --extra-vars "ssh_key_path=.ssh/id_rsa.pub"
- name: add ssh key alternative
  authorized_key:
    user={{ user }}
    key="{{ lookup('file', lookup('env','HOME') + ssh_key_path) }}"
    state=present
  when: ssh_key_path is defined

- name: add custom sudoer file
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ user }}"
    mode: 0440
